{{- range $key, $val := $.Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $key }}
{{- if $.Values.argocd.enabled }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.argocd.controller }}
{{- end }}
{{- end }}